apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: demo-voting-app
    name: redis-pod
  name: redis-pod
spec:
  containers:
  - image: redis
    name: redis-pod
    ports:
    - containerPort: 6379
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
