apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: sample-voting-app
    name: worker-app-pod
  name: worker-app-pod
  namespace: voting
spec:
  containers:
  - image: dockersamples/examplevotingapp_worker
    name: worker-app-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
