apiVersion: v1
kind: Pod
metadata:
  labels:
    name: postgres-pod
    app: sample-voting-app
  name: postgres-pod
  namespace: voting
spec:
  containers:
  - env:
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_PASSWORD
      value: postgres
    image: postgres
    name: postgres-pod
    ports:
    - containerPort: 5432
