apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: postgres-service
    app: sample-voting-app
  name: db
  namespace: voting
spec:
  ports:
  - name: dbport
    port: 5432
    targetPort: 5432
  selector:
    app: sample-voting-app
    name: postgres-pod
  type: ClusterIP
