apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  namespace: voting
  labels:
    app: sample-voting-app
    name: voting-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-voting-app
      name: voting-app-pod
  template:
    metadata:
      labels:
        app: sample-voting-app
        name: voting-app-pod
    spec:
      containers:
      - name: voting-app-pod
        image: dockersamples/examplevotingapp_vote
        ports:
        - containerPort: 80

