apiVersion: v1
kind: Service
metadata:
  labels:
    name: voting-service
    app: sample-voting-app
  name: voting-service
  namespace: voting
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30004
  selector:
    app: sample-voting-app
    name: voting-app-pod
  type: LoadBalancer
