apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  namespace: voting
  labels:
    app: sample-voting-app
    name: result-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-voting-app
      name: result-app-pod
  template:
    metadata:
      labels:
        app: sample-voting-app
        name: result-app-pod
    spec:
      containers:
      - name: result-app-pod
        image: dockersamples/examplevotingapp_result
        ports:
        - containerPort: 80

