apiVersion: v1
kind: Pod
metadata:
  labels:
    app: sample-voting-app
    name: result-app-pod
  name: result-app-pod
  namespace: voting
spec:
  containers:
  - image: dockersamples/examplevotingapp_result
    name: result-app-pod
    ports:
    - containerPort: 80
