apiVersion: v1
kind: Service
metadata:
  labels:
    name: result-service
    app: sample-voting-app
  name: result-service
  namespace: voting
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30005
  selector:
    name: result-app-pod
    app: sample-voting-app
  type: LoadBalancer
