apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: voting-app-deploy
    app: demo-voting-app
  name: voting-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-voting-app
      name: voting-app-pod
  template:
    metadata:
      name: voting-app-pod
      labels:
        app: demo-voting-app
        name: voting-app-pod 
    spec:
      containers:
        - name: voting-app
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80
