apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: worker-app-deploy
    app: demo-voting-app
  name: worker-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-voting-app
      name: worker-app-pod
  template:
    metadata:
      name: worker-app-pod
      labels:
        app: demo-voting-app 
        name: worker-app-pod
    spec:
      containers:
        - name: worker-app
          image: dockersamples/examplevotingapp_worker
