apiVersion: v1
kind: Pod
metadata:
  labels:
    name: redis-pod
    app: sample-voting-app
  name: redis-pod
  namespace: voting
spec:
  containers:
  - image: redis
    name: redis-pod
    ports:
    - containerPort: 6379
