apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis-service
    app: sample-voting-app
  name: redis
  namespace: voting
spec:
  ports:
  - name: redisport
    port: 6379
    targetPort: 6379
  selector:
    name: redis-pod
    app: sample-voting-app
  type: ClusterIP
